/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValidatorRouteImport } from './routes/validator'
import { Route as DispatcherRouteImport } from './routes/dispatcher'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminFieldsRouteImport } from './routes/admin.fields'

const ValidatorRoute = ValidatorRouteImport.update({
  id: '/validator',
  path: '/validator',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatcherRoute = DispatcherRouteImport.update({
  id: '/dispatcher',
  path: '/dispatcher',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFieldsRoute = AdminFieldsRouteImport.update({
  id: '/admin/fields',
  path: '/admin/fields',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dispatcher': typeof DispatcherRoute
  '/validator': typeof ValidatorRoute
  '/admin/fields': typeof AdminFieldsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dispatcher': typeof DispatcherRoute
  '/validator': typeof ValidatorRoute
  '/admin/fields': typeof AdminFieldsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/dispatcher': typeof DispatcherRoute
  '/validator': typeof ValidatorRoute
  '/admin/fields': typeof AdminFieldsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/dispatcher' | '/validator' | '/admin/fields'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/dispatcher' | '/validator' | '/admin/fields'
  id: '__root__' | '/' | '/app' | '/dispatcher' | '/validator' | '/admin/fields'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  DispatcherRoute: typeof DispatcherRoute
  ValidatorRoute: typeof ValidatorRoute
  AdminFieldsRoute: typeof AdminFieldsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/validator': {
      id: '/validator'
      path: '/validator'
      fullPath: '/validator'
      preLoaderRoute: typeof ValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatcher': {
      id: '/dispatcher'
      path: '/dispatcher'
      fullPath: '/dispatcher'
      preLoaderRoute: typeof DispatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fields': {
      id: '/admin/fields'
      path: '/admin/fields'
      fullPath: '/admin/fields'
      preLoaderRoute: typeof AdminFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  DispatcherRoute: DispatcherRoute,
  ValidatorRoute: ValidatorRoute,
  AdminFieldsRoute: AdminFieldsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
